-- Disable RLS on all tables so anon key can read/write
-- (app uses its own simple auth, not Supabase Auth)

ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE subject_list DISABLE ROW LEVEL SECURITY;
ALTER TABLE committee_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE teachers DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE periods DISABLE ROW LEVEL SECURITY;
ALTER TABLE period_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE incomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE submission_items DISABLE ROW LEVEL SECURITY;
